# Generated by Django 4.1.5 on 2023-01-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='actvation_code',
            new_name='activation_code',
        ),
    ]
